version: "3.8"
services:
  db:
    build: ./database
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: ebike
      MYSQL_USER: user
      MYSQL_HOST: localhost
    ports:
      - "3307:3306"
    expose:
      - 3307
    restart: always
    healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            timeout: 20s
            retries: 10
    networks:
      - app-network
  web:
    build: ./cykel
    environment:
      MYSQL_DATABASE: ebike
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_HOST: db
    ports:
      - "1337:1337"
      - "5000:5000"
    links:
      - db:db
    depends_on:
      db: 
        condition: service_healthy
    restart: on-failure
    networks:
      - app-network
  laravel:
    build: ./laravel
    environment:
      MYSQL_DATABASE: ebike
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_HOST: db
    ports:
      - "8000:8000"
      - "4000:5000"
    links:
      - db:db
      - web:web
    depends_on:
      db:
        condition: service_healthy
      web:
        condition: service_started
    restart: on-failure
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
