version: "3.8"
services:
  mysql:
    build: ./database
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: ebike
      MYSQL_USER: user
      MYSQL_HOST: localhost
    ports:
      - "3307:3306"
    restart: always
    healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            timeout: 20s
            retries: 10
    networks:
      - app-network
  express:
    build: ./cykel
    environment:
      DB_CONFIG: docker
    ports:
      - "1337:1337"
      - "5000:5000"
    depends_on:
      mysql: 
        condition: service_healthy
    restart: on-failure
    networks:
      - app-network
  laravel:
    build: ./laravel
    environment:
      APP_ENV: docker
    ports:
      - "8000:8000"
      - "8001:5000"
    depends_on:
      mysql:
        condition: service_healthy
      express:
        condition: service_started
    restart: on-failure
    networks:
      - app-network
  customers:
    build: ./customers
    depends_on:
      mysql:
        condition: service_healthy
      express: 
        condition: service_started
      laravel:
        condition: service_started
    restart: on-failure
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
